from header_common import *
from header_operations import *
from header_parties import *
from header_items import *
from header_skills import *
from header_triggers import *
from header_troops import *

from module_constants import *

####################################################################################################################
#  Each trigger contains the following fields:
# 1) Check interval: How frequently this trigger will be checked
# 2) Delay interval: Time to wait before applying the consequences of the trigger
#    After its conditions have been evaluated as true.
# 3) Re-arm interval. How much time must pass after applying the consequences of the trigger for the trigger to become active again.
#    You can put the constant ti_once here to make sure that the trigger never becomes active again after it fires once.
# 4) Conditions block (list). This must be a valid operation block. See header_operations.py for reference.
#    Every time the trigger is checked, the conditions block will be executed.
#    If the conditions block returns true, the consequences block will be executed.
#    If the conditions block is empty, it is assumed that it always evaluates to true.
# 5) Consequences block (list). This must be a valid operation block. See header_operations.py for reference. 
####################################################################################################################

# Some constants for use below
merchant_inventory_space = 30
num_merchandise_goods = 36



triggers = [
	(0.1, 0.0, ti_once,
		[
			(map_free, 0)
		],

		[
			(dialog_box, "str_tutorial_map1")
		]),

	(0.0, 0.0, 0.0,
		[
			(map_free),
			(neq, "$g_player_troop", "trp_player")
		],

		[
			(assign, "$g_player_troop", "trp_player"),
			(set_player_troop, "$g_player_troop")
		]),

	(24.0, 0.0, 0.0,
		[],

		[]),

	(0.1, 0.0, 0.0,
		[],

		[
			(troop_set_health, "trp_knight_2_23", 0),
			(troop_set_health, "trp_knight_2_24", 0),
			(troop_set_health, "trp_knight_3_25", 0),
			(troop_set_health, "trp_knight_6_20", 0),
			(troop_set_health, "trp_knight_6_21", 0),
			(troop_set_health, "trp_knight_6_22", 0),
			(troop_set_health, "trp_knight_9_43", 0),
			(troop_set_health, "trp_knight_10_26", 0)
		]),

	(0.0, 0.0, 168.0,
		[],

		[
			(call_script, "script_refresh_center_inventories")
		]),

	(0.0, 0.0, 168.0,
		[],

		[
			(call_script, "script_refresh_center_armories")
		]),

	(0.0, 0.0, 168.0,
		[],

		[
			(call_script, "script_refresh_center_weaponsmiths")
		]),

	(0.0, 0.0, 168.0,
		[],

		[
			(call_script, "script_refresh_center_stables")
		]),

	(5.7, 0.0, 0.0,
		[
			(try_begin),
				(eq, "$troop_trees", "trp_troop_tree_0"),
				(store_num_parties_of_template, reg2, "pt_manhunters"),
			(else_try),
				(eq, "$troop_trees", "trp_troop_tree_1"),
				(store_num_parties_of_template, reg2, "pt_manhunters_r"),
			(else_try),
				(eq, "$troop_trees", "trp_troop_tree_2"),
				(store_num_parties_of_template, reg2, "pt_manhunters_e"),
			(try_end),
			(store_num_parties_of_template, reg2, "pt_manhunters"),
			(lt, reg2, 4)
		],

		[
			(set_spawn_radius, 1),
			(store_add, ":value", "p_town_23", 1),
			(store_random_in_range, ":random_in_range_town_1_value", "p_town_1", ":value"),
			(try_begin),
				(eq, "$troop_trees", "trp_troop_tree_0"),
				(spawn_around_party, ":random_in_range_town_1_value", "pt_manhunters"),
			(else_try),
				(eq, "$troop_trees", "trp_troop_tree_1"),
				(spawn_around_party, ":random_in_range_town_1_value", "pt_manhunters_r"),
			(else_try),
				(eq, "$troop_trees", "trp_troop_tree_2"),
				(spawn_around_party, ":random_in_range_town_1_value", "pt_manhunters_e"),
			(try_end)
		]),

	(1.0, 0.0, 0.0,
		[
			(check_quest_active, "qst_track_down_bandits"),
			(neg|check_quest_failed, "qst_track_down_bandits"),
			(neg|check_quest_succeeded, "qst_track_down_bandits")
		],

		[
			(quest_get_slot, ":track_down_bandits_target_party", "qst_track_down_bandits", slot_quest_target_party),
			(try_begin),
				(party_is_active, ":track_down_bandits_target_party"),
				(store_faction_of_party, ":faction_of_party_track_down_bandits_target_party", ":track_down_bandits_target_party"),
				(neg|is_between, ":faction_of_party_track_down_bandits_target_party", "fac_player_supporters_faction", "fac_kingdoms_end"),
				(assign, ":value", 8),
				(try_begin),
					(is_currently_night),
					(assign, ":value", 5),
				(try_end),
				(try_for_parties, ":var_4"),
					(gt, ":var_4", "p_spawn_points_end"),
					(store_faction_of_party, ":faction_of_party_var_4", ":var_4"),
					(is_between, ":faction_of_party_var_4", "fac_player_supporters_faction", "fac_kingdoms_end"),
					(store_distance_to_party_from_party, ":distance_to_party_from_party_var_4_track_down_bandits_target_party", ":var_4", ":track_down_bandits_target_party"),
					(lt, ":distance_to_party_from_party_var_4_track_down_bandits_target_party", ":value"),
					(try_begin),
						(eq, "$cheat_mode", 1),
						(str_store_party_name, 4, ":var_4"),
						(display_message, "@{!}DEBUG -- Wanted bandits spotted by {s4}"),
					(try_end),
					(call_script, "script_get_closest_center", ":track_down_bandits_target_party"),
					(assign, ":var_7", reg0),
					(call_script, "script_add_log_entry", 70, ":var_4", ":var_7", ":track_down_bandits_target_party", -1),
				(try_end),
			(else_try),
				(display_message, "str_bandits_eliminated_by_another"),
				(call_script, "script_abort_quest", "qst_track_down_bandits", 0),
			(try_end)
		]),

	(2.0, 0.0, 0.0,
		[
			(store_random_party_of_template, reg2, "pt_prisoner_train_party"),
			(party_is_in_any_town, reg2)
		],

		[
			(store_faction_of_party, ":faction_of_party_reg2", reg2),
			(call_script, "script_cf_select_random_walled_center_with_faction", ":faction_of_party_reg2", -1),
			(party_set_ai_behavior, reg2, 1),
			(party_set_ai_object, reg2, reg0),
			(party_set_flags, reg2, 65536, 0)
		]),

	(4.0, 0.0, 0.0,
		[
			(eq, "$caravan_escort_state", 1),
			(assign, ":value", 0),
			(try_begin),
				(neg|party_is_active, "$caravan_escort_party_id"),
				(assign, ":value", 1),
			(else_try),
				(get_party_ai_object, ":party_ai_object_caravan_escort_party_id", "$caravan_escort_party_id"),
				(neq, ":party_ai_object_caravan_escort_party_id", "$caravan_escort_destination_town"),
				(assign, ":value", 1),
			(try_end),
			(eq, ":value", 1)
		],

		[
			(assign, "$caravan_escort_state", 0)
		]),

	(1.5, 0.0, 0.0,
		[
			(store_random_party_of_template, reg2, "pt_messenger_party"),
			(party_is_in_any_town, reg2)
		],

		[
			(store_faction_of_party, ":faction_of_party_reg2", reg2),
			(call_script, "script_cf_select_random_walled_center_with_faction", ":faction_of_party_reg2", -1),
			(party_set_ai_behavior, reg2, 1),
			(party_set_ai_object, reg2, reg0),
			(party_set_flags, reg2, 65536, 0)
		]),

	(1.0, 0.0, 0.0,
		[],

		[
			(try_for_range, ":faction", "fac_player_supporters_faction", "fac_kingdoms_end"),
				(faction_slot_eq, ":faction", slot_faction_state, 0),
				(try_begin),
					(store_random_in_range, ":random_in_range_0_100", 0, 100),
					(lt, ":random_in_range_0_100", 10),
					(call_script, "script_create_kingdom_party_if_below_limit", ":faction", 11),
				(try_end),
				(try_begin),
					(store_random_in_range, ":random_in_range_0_100", 0, 100),
					(lt, ":random_in_range_0_100", 10),
					(call_script, "script_create_kingdom_party_if_below_limit", ":faction", 14),
				(try_end),
			(try_end)
		]),

	(0.2, 0.0, 0.0,
		[
			(check_quest_active, "qst_incriminate_loyal_commander"),
			(neg|check_quest_concluded, "qst_incriminate_loyal_commander"),
			(quest_slot_eq, "qst_incriminate_loyal_commander", slot_quest_current_state, 2),
			(quest_get_slot, ":incriminate_loyal_commander_target_center", "qst_incriminate_loyal_commander", slot_quest_target_center),
			(quest_get_slot, ":incriminate_loyal_commander_target_party", "qst_incriminate_loyal_commander", slot_quest_target_party),
			(try_begin),
				(neg|party_is_active, ":incriminate_loyal_commander_target_party"),
				(quest_set_slot, "qst_incriminate_loyal_commander", slot_quest_current_state, 3),
				(call_script, "script_fail_quest", "qst_incriminate_loyal_commander"),
			(else_try),
				(party_is_in_town, ":incriminate_loyal_commander_target_party", ":incriminate_loyal_commander_target_center"),
				(remove_party, ":incriminate_loyal_commander_target_party"),
				(quest_set_slot, "qst_incriminate_loyal_commander", slot_quest_current_state, 3),
				(quest_get_slot, ":incriminate_loyal_commander_object_troop", "qst_incriminate_loyal_commander", slot_quest_object_troop),
				(assign, ":var_4", 0),
				(try_for_range, ":faction", "fac_player_supporters_faction", "fac_kingdoms_end"),
					(faction_slot_eq, ":faction", slot_faction_state, 0),
					(neq, ":faction", "fac_player_supporters_faction"),
					(neg|quest_slot_eq, "qst_incriminate_loyal_commander", slot_quest_target_faction, ":faction"),
					(val_add, ":var_4", 1),
				(try_end),
				(try_begin),
					(gt, ":var_4", 0),
					(store_random_in_range, ":random_in_range_0_var_4", 0, ":var_4"),
					(assign, ":value", -1),
					(try_for_range, ":faction", "fac_player_supporters_faction", "fac_kingdoms_end"),
						(eq, ":value", -1),
						(faction_slot_eq, ":faction", slot_faction_state, 0),
						(neq, ":faction", "fac_player_supporters_faction"),
						(neg|quest_slot_eq, "qst_incriminate_loyal_commander", slot_quest_target_faction, ":faction"),
						(val_sub, ":random_in_range_0_var_4", 1),
						(lt, ":random_in_range_0_var_4", 0),
						(assign, ":value", ":faction"),
					(try_end),
				(try_end),
				(try_begin),
					(gt, ":value", 0),
					(call_script, "script_change_troop_faction", ":incriminate_loyal_commander_object_troop", ":value"),
				(else_try),
					(call_script, "script_change_troop_faction", ":incriminate_loyal_commander_object_troop", "fac_robber_knights"),
				(try_end),
				(call_script, "script_succeed_quest", "qst_incriminate_loyal_commander"),
			(try_end)
		],

		[]),

	(0.2, 0.0, 0.0,
		[
			(check_quest_active, "qst_bring_back_runaway_serfs"),
			(neg|check_quest_concluded, "qst_bring_back_runaway_serfs"),
			(quest_get_slot, ":bring_back_runaway_serfs_object_center", "qst_bring_back_runaway_serfs", slot_quest_object_center),
			(quest_get_slot, ":bring_back_runaway_serfs_target_center", "qst_bring_back_runaway_serfs", slot_quest_target_center),
			(try_begin),
				(party_is_active, "$qst_bring_back_runaway_serfs_party_1"),
				(try_begin),
					(party_is_in_town, "$qst_bring_back_runaway_serfs_party_1", ":bring_back_runaway_serfs_target_center"),
					(remove_party, "$qst_bring_back_runaway_serfs_party_1"),
					(val_add, "$qst_bring_back_runaway_serfs_num_parties_fleed", 1),
				(else_try),
					(party_is_in_town, "$qst_bring_back_runaway_serfs_party_1", ":bring_back_runaway_serfs_object_center"),
					(remove_party, "$qst_bring_back_runaway_serfs_party_1"),
					(val_add, "$qst_bring_back_runaway_serfs_num_parties_returned", 1),
				(else_try),
					(store_distance_to_party_from_party, ":distance_to_party_from_party_main_party_qst_bring_back_runaway_serfs_party_1", "p_main_party", "$qst_bring_back_runaway_serfs_party_1"),
					(gt, ":distance_to_party_from_party_main_party_qst_bring_back_runaway_serfs_party_1", 3),
					(party_set_ai_object, "$qst_bring_back_runaway_serfs_party_1", ":bring_back_runaway_serfs_target_center"),
				(try_end),
			(try_end),
			(try_begin),
				(party_is_active, "$qst_bring_back_runaway_serfs_party_2"),
				(try_begin),
					(party_is_in_town, "$qst_bring_back_runaway_serfs_party_2", ":bring_back_runaway_serfs_target_center"),
					(remove_party, "$qst_bring_back_runaway_serfs_party_2"),
					(val_add, "$qst_bring_back_runaway_serfs_num_parties_fleed", 1),
				(else_try),
					(party_is_in_town, "$qst_bring_back_runaway_serfs_party_2", ":bring_back_runaway_serfs_object_center"),
					(remove_party, "$qst_bring_back_runaway_serfs_party_2"),
					(val_add, "$qst_bring_back_runaway_serfs_num_parties_returned", 1),
				(else_try),
					(store_distance_to_party_from_party, ":distance_to_party_from_party_main_party_qst_bring_back_runaway_serfs_party_1", "p_main_party", "$qst_bring_back_runaway_serfs_party_2"),
					(gt, ":distance_to_party_from_party_main_party_qst_bring_back_runaway_serfs_party_1", 3),
					(party_set_ai_object, "$qst_bring_back_runaway_serfs_party_2", ":bring_back_runaway_serfs_target_center"),
				(try_end),
			(try_end),
			(try_begin),
				(party_is_active, "$qst_bring_back_runaway_serfs_party_3"),
				(try_begin),
					(party_is_in_town, "$qst_bring_back_runaway_serfs_party_3", ":bring_back_runaway_serfs_target_center"),
					(remove_party, "$qst_bring_back_runaway_serfs_party_3"),
					(val_add, "$qst_bring_back_runaway_serfs_num_parties_fleed", 1),
				(else_try),
					(party_is_in_town, "$qst_bring_back_runaway_serfs_party_3", ":bring_back_runaway_serfs_object_center"),
					(remove_party, "$qst_bring_back_runaway_serfs_party_3"),
					(val_add, "$qst_bring_back_runaway_serfs_num_parties_returned", 1),
				(else_try),
					(store_distance_to_party_from_party, ":distance_to_party_from_party_main_party_qst_bring_back_runaway_serfs_party_1", "p_main_party", "$qst_bring_back_runaway_serfs_party_3"),
					(gt, ":distance_to_party_from_party_main_party_qst_bring_back_runaway_serfs_party_1", 3),
					(party_set_ai_object, "$qst_bring_back_runaway_serfs_party_3", ":bring_back_runaway_serfs_target_center"),
				(try_end),
			(try_end),
			(assign, ":var_4", "$qst_bring_back_runaway_serfs_num_parties_returned"),
			(val_add, ":var_4", "$qst_bring_back_runaway_serfs_num_parties_fleed"),
			(ge, ":var_4", 3),
			(try_begin),
				(ge, "$qst_bring_back_runaway_serfs_num_parties_returned", 3),
				(call_script, "script_succeed_quest", "qst_bring_back_runaway_serfs"),
			(else_try),
				(eq, "$qst_bring_back_runaway_serfs_num_parties_returned", 0),
				(call_script, "script_fail_quest", "qst_bring_back_runaway_serfs"),
			(else_try),
				(call_script, "script_conclude_quest", "qst_bring_back_runaway_serfs"),
			(try_end)
		],

		[]),

	(0.2, 0.0, 0.0,
		[
			(check_quest_active, "qst_hunt_down_smugglers"),
			(neg|check_quest_concluded, "qst_hunt_down_smugglers"),
			(quest_get_slot, ":hunt_down_smugglers_object_center", "qst_hunt_down_smugglers", slot_quest_object_center),
			(quest_get_slot, ":hunt_down_smugglers_target_center", "qst_hunt_down_smugglers", slot_quest_target_center),
			(try_begin),
				(party_is_active, "$qst_hunt_down_smugglers_party_1"),
				(try_begin),
					(party_is_in_town, "$qst_hunt_down_smugglers_party_1", ":hunt_down_smugglers_target_center"),
					(remove_party, "$qst_hunt_down_smugglers_party_1"),
					(val_add, "$qst_hunt_down_smugglers_num_parties_fleed", 1),
				(else_try),
					(party_is_in_town, "$qst_hunt_down_smugglers_party_1", ":hunt_down_smugglers_object_center"),
					(remove_party, "$qst_hunt_down_smugglers_party_1"),
					(val_add, "$qst_hunt_down_smugglers_num_parties_returned", 1),
				(else_try),
					(store_distance_to_party_from_party, ":distance_to_party_from_party_main_party_qst_hunt_down_smugglers_party_1", "p_main_party", "$qst_hunt_down_smugglers_party_1"),
					(gt, ":distance_to_party_from_party_main_party_qst_hunt_down_smugglers_party_1", 3),
					(party_set_ai_object, "$qst_hunt_down_smugglers_party_1", ":hunt_down_smugglers_target_center"),
				(try_end),
			(try_end),
			(try_begin),
				(party_is_active, "$qst_hunt_down_smugglers_party_2"),
				(try_begin),
					(party_is_in_town, "$qst_hunt_down_smugglers_party_2", ":hunt_down_smugglers_target_center"),
					(remove_party, "$qst_hunt_down_smugglers_party_2"),
					(val_add, "$qst_hunt_down_smugglers_num_parties_fleed", 1),
				(else_try),
					(party_is_in_town, "$qst_hunt_down_smugglers_party_2", ":hunt_down_smugglers_object_center"),
					(remove_party, "$qst_hunt_down_smugglers_party_2"),
					(val_add, "$qst_hunt_down_smugglers_num_parties_returned", 1),
				(else_try),
					(store_distance_to_party_from_party, ":distance_to_party_from_party_main_party_qst_hunt_down_smugglers_party_1", "p_main_party", "$qst_hunt_down_smugglers_party_2"),
					(gt, ":distance_to_party_from_party_main_party_qst_hunt_down_smugglers_party_1", 3),
					(party_set_ai_object, "$qst_hunt_down_smugglers_party_2", ":hunt_down_smugglers_target_center"),
				(try_end),
			(try_end),
			(try_begin),
				(party_is_active, "$qst_hunt_down_smugglers_party_3"),
				(try_begin),
					(party_is_in_town, "$qst_hunt_down_smugglers_party_3", ":hunt_down_smugglers_target_center"),
					(remove_party, "$qst_hunt_down_smugglers_party_3"),
					(val_add, "$qst_hunt_down_smugglers_num_parties_fleed", 1),
				(else_try),
					(party_is_in_town, "$qst_hunt_down_smugglers_party_3", ":hunt_down_smugglers_object_center"),
					(remove_party, "$qst_hunt_down_smugglers_party_3"),
					(val_add, "$qst_hunt_down_smugglers_num_parties_returned", 1),
				(else_try),
					(store_distance_to_party_from_party, ":distance_to_party_from_party_main_party_qst_hunt_down_smugglers_party_1", "p_main_party", "$qst_hunt_down_smugglers_party_3"),
					(gt, ":distance_to_party_from_party_main_party_qst_hunt_down_smugglers_party_1", 3),
					(party_set_ai_object, "$qst_hunt_down_smugglers_party_3", ":hunt_down_smugglers_target_center"),
				(try_end),
			(try_end),
			(assign, ":var_4", "$qst_hunt_down_smugglers_num_parties_returned"),
			(val_add, ":var_4", "$qst_hunt_down_smugglers_num_parties_fleed"),
			(ge, ":var_4", 3),
			(try_begin),
				(ge, "$qst_hunt_down_smugglers_num_parties_returned", 3),
				(call_script, "script_succeed_quest", "qst_hunt_down_smugglers"),
			(else_try),
				(eq, "$qst_hunt_down_smugglers_num_parties_returned", 0),
				(call_script, "script_fail_quest", "qst_hunt_down_smugglers"),
			(else_try),
				(call_script, "script_conclude_quest", "qst_hunt_down_smugglers"),
			(try_end)
		],

		[]),

	(0.5, 0.0, 0.0,
		[
			(check_quest_active, "qst_follow_spy"),
			(eq, "$qst_follow_spy_no_active_parties", 0),
			(quest_get_slot, ":follow_spy_giver_center", "qst_follow_spy", slot_quest_giver_center),
			(quest_get_slot, ":follow_spy_object_center", "qst_follow_spy", slot_quest_object_center),
			(assign, ":value", 0),
			(try_begin),
				(this_or_next|ge, "$qst_follow_spy_run_away", 2),
				(this_or_next|neg|party_is_active, "$qst_follow_spy_spy_party"),
				(neg|party_is_active, "$qst_follow_spy_spy_partners_party"),
			(else_try),
				(eq, "$qst_follow_spy_meeting_state", 0),
				(store_distance_to_party_from_party, ":distance_to_party_from_party_main_party_qst_follow_spy_spy_party", "p_main_party", "$qst_follow_spy_spy_party"),
				(try_begin),
					(assign, ":value_2", 3),
					(try_begin),
						(is_currently_night),
						(assign, ":value_2", 1),
					(try_end),
					(le, ":distance_to_party_from_party_main_party_qst_follow_spy_spy_party", ":value_2"),
					(store_distance_to_party_from_party, ":distance_to_party_from_party_main_party_follow_spy_giver_center", "p_main_party", ":follow_spy_giver_center"),
					(gt, ":distance_to_party_from_party_main_party_follow_spy_giver_center", 1),
					(val_add, "$qst_follow_spy_run_away", 1),
					(try_begin),
						(eq, "$qst_follow_spy_run_away", 2),
						(assign, ":value", 1),
						(display_message, "str_qst_follow_spy_noticed_you"),
					(try_end),
				(else_try),
					(store_distance_to_party_from_party, ":distance_to_party_from_party_main_party_qst_follow_spy_spy_party", "$qst_follow_spy_spy_partners_party", "$qst_follow_spy_spy_party"),
					(le, ":distance_to_party_from_party_main_party_qst_follow_spy_spy_party", 1),
					(party_attach_to_party, "$qst_follow_spy_spy_party", "$qst_follow_spy_spy_partners_party"),
					(assign, "$qst_follow_spy_meeting_state", 1),
					(assign, "$qst_follow_spy_meeting_counter", 0),
				(try_end),
			(else_try),
				(eq, "$qst_follow_spy_meeting_state", 1),
				(store_distance_to_party_from_party, ":distance_to_party_from_party_main_party_qst_follow_spy_spy_party", "p_main_party", "$qst_follow_spy_spy_partners_party"),
				(try_begin),
					(le, ":distance_to_party_from_party_main_party_qst_follow_spy_spy_party", 1),
					(party_detach, "$qst_follow_spy_spy_party"),
					(val_add, "$qst_follow_spy_run_away", 1),
					(try_begin),
						(eq, "$qst_follow_spy_run_away", 2),
						(assign, ":value", 1),
						(display_message, "str_qst_follow_spy_noticed_you"),
					(try_end),
				(else_try),
					(val_add, "$qst_follow_spy_meeting_counter", 1),
					(gt, "$qst_follow_spy_meeting_counter", 4),
					(party_detach, "$qst_follow_spy_spy_party"),
					(assign, ":value", 1),
					(assign, "$qst_follow_spy_meeting_state", 2),
				(try_end),
			(try_end),
			(try_begin),
				(eq, ":value", 1),
				(party_set_ai_object, "$qst_follow_spy_spy_party", ":follow_spy_giver_center"),
				(party_set_ai_object, "$qst_follow_spy_spy_partners_party", ":follow_spy_object_center"),
				(party_set_ai_behavior, "$qst_follow_spy_spy_party", 1),
				(party_set_ai_behavior, "$qst_follow_spy_spy_partners_party", 1),
				(party_set_flags, "$qst_follow_spy_spy_party", 65536, 0),
				(party_set_flags, "$qst_follow_spy_spy_partners_party", 65536, 0),
			(try_end),
			(assign, ":var_7", 0),
			(try_begin),
				(party_is_active, "$qst_follow_spy_spy_party"),
				(val_add, ":var_7", 1),
				(party_is_in_town, "$qst_follow_spy_spy_party", ":follow_spy_giver_center"),
				(remove_party, "$qst_follow_spy_spy_party"),
				(assign, "$qst_follow_spy_spy_back_in_town", 1),
				(val_sub, ":var_7", 1),
			(try_end),
			(try_begin),
				(party_is_active, "$qst_follow_spy_spy_partners_party"),
				(val_add, ":var_7", 1),
				(party_is_in_town, "$qst_follow_spy_spy_partners_party", ":follow_spy_object_center"),
				(remove_party, "$qst_follow_spy_spy_partners_party"),
				(assign, "$qst_follow_spy_partner_back_in_town", 1),
				(val_sub, ":var_7", 1),
			(try_end),
			(try_begin),
				(eq, "$qst_follow_spy_partner_back_in_town", 1),
				(eq, "$qst_follow_spy_spy_back_in_town", 1),
				(call_script, "script_fail_quest", "qst_follow_spy"),
			(try_end),
			(try_begin),
				(eq, ":var_7", 0),
				(assign, "$qst_follow_spy_no_active_parties", 1),
				(party_count_prisoners_of_type, ":var_8", "p_main_party", "trp_spy"),
				(party_count_prisoners_of_type, ":var_9", "p_main_party", "trp_spy_partner"),
				(gt, ":var_8", 0),
				(gt, ":var_9", 0),
				(call_script, "script_succeed_quest", "qst_follow_spy"),
			(try_end)
		],

		[]),

	(168.0, 0.0, 0.0,
		[],

		[
			(val_mul, "$debt_to_merchants_guild", 101),
			(val_div, "$debt_to_merchants_guild", 100)
		]),

	(0.1, 0.0, 0.1,
		[
			(check_quest_active, "qst_escort_merchant_caravan"),
			(eq, "$escort_merchant_caravan_mode", 1)
		],

		[
			(quest_get_slot, ":escort_merchant_caravan_target_party", "qst_escort_merchant_caravan", slot_quest_target_party),
			(try_begin),
				(party_is_active, ":escort_merchant_caravan_target_party"),
				(party_set_ai_behavior, ":escort_merchant_caravan_target_party", 0),
				(party_set_flags, ":escort_merchant_caravan_target_party", 65536, 0),
			(try_end)
		]),

	(0.1, 0.0, 0.1,
		[
			(check_quest_active, "qst_escort_merchant_caravan"),
			(eq, "$escort_merchant_caravan_mode", 0)
		],

		[
			(quest_get_slot, ":escort_merchant_caravan_target_party", "qst_escort_merchant_caravan", slot_quest_target_party),
			(try_begin),
				(party_is_active, ":escort_merchant_caravan_target_party"),
				(party_set_ai_behavior, ":escort_merchant_caravan_target_party", 10),
				(party_set_flags, ":escort_merchant_caravan_target_party", 65536, 0),
				(party_set_ai_object, ":escort_merchant_caravan_target_party", "p_main_party"),
			(try_end)
		]),

	(0.1, 0.0, 0.0,
		[
			(check_quest_active, "qst_escort_merchant_caravan"),
			(quest_get_slot, ":escort_merchant_caravan_target_party", "qst_escort_merchant_caravan", slot_quest_target_party),
			(neg|party_is_active, ":escort_merchant_caravan_target_party")
		],

		[
			(call_script, "script_abort_quest", "qst_escort_merchant_caravan", 2)
		]),

	(0.3, 0.0, 1.1,
		[
			(check_quest_active, "qst_troublesome_bandits"),
			(neg|check_quest_failed, "qst_troublesome_bandits"),
			(try_begin),
				(eq, "$troop_trees", "trp_troop_tree_0"),
				(store_num_parties_destroyed, ":num_parties_destroyed_troublesome_bandits", "pt_troublesome_bandits"),
				(store_num_parties_destroyed_by_player, ":num_parties_destroyed_by_player_troublesome_bandits", "pt_troublesome_bandits"),
			(else_try),
				(eq, "$troop_trees", "trp_troop_tree_1"),
				(store_num_parties_destroyed, ":num_parties_destroyed_troublesome_bandits", "pt_troublesome_bandits_r"),
				(store_num_parties_destroyed_by_player, ":num_parties_destroyed_by_player_troublesome_bandits", "pt_troublesome_bandits_r"),
			(else_try),
				(eq, "$troop_trees", "trp_troop_tree_2"),
				(store_num_parties_destroyed, ":num_parties_destroyed_troublesome_bandits", "pt_troublesome_bandits_e"),
				(store_num_parties_destroyed_by_player, ":num_parties_destroyed_by_player_troublesome_bandits", "pt_troublesome_bandits_e"),
			(try_end),
			(lt, "$qst_troublesome_bandits_eliminated", ":num_parties_destroyed_troublesome_bandits"),
			(eq, ":num_parties_destroyed_by_player_troublesome_bandits", "$qst_troublesome_bandits_eliminated_by_player")
		],

		[
			(display_message, "str_bandits_eliminated_by_another"),
			(call_script, "script_abort_quest", "qst_troublesome_bandits", 0)
		]),

	(0.3, 0.0, 1.1,
		[
			(check_quest_active, "qst_troublesome_bandits"),
			(neg|check_quest_succeeded, "qst_troublesome_bandits"),
			(try_begin),
				(eq, "$troop_trees", "trp_troop_tree_0"),
				(store_num_parties_destroyed, ":num_parties_destroyed_troublesome_bandits", "pt_troublesome_bandits"),
				(store_num_parties_destroyed_by_player, ":num_parties_destroyed_by_player_troublesome_bandits", "pt_troublesome_bandits"),
			(else_try),
				(eq, "$troop_trees", "trp_troop_tree_1"),
				(store_num_parties_destroyed, ":num_parties_destroyed_troublesome_bandits", "pt_troublesome_bandits_r"),
				(store_num_parties_destroyed_by_player, ":num_parties_destroyed_by_player_troublesome_bandits", "pt_troublesome_bandits_r"),
			(else_try),
				(eq, "$troop_trees", "trp_troop_tree_2"),
				(store_num_parties_destroyed, ":num_parties_destroyed_troublesome_bandits", "pt_troublesome_bandits_e"),
				(store_num_parties_destroyed_by_player, ":num_parties_destroyed_by_player_troublesome_bandits", "pt_troublesome_bandits_e"),
			(try_end),
			(lt, "$qst_troublesome_bandits_eliminated", ":num_parties_destroyed_troublesome_bandits"),
			(neq, ":num_parties_destroyed_by_player_troublesome_bandits", "$qst_troublesome_bandits_eliminated_by_player")
		],

		[
			(call_script, "script_succeed_quest", "qst_troublesome_bandits")
		]),

	(0.3, 0.0, 1.1,
		[
			(check_quest_active, "qst_beowulf_quest4"),
			(store_num_parties_destroyed, ":num_parties_destroyed_beowulf_warband", "pt_beowulf_warband"),
			(lt, "$qst_cheese_rustlers_eliminated", ":num_parties_destroyed_beowulf_warband"),
			(store_num_parties_destroyed_by_player, ":num_parties_destroyed_by_player_beowulf_warband", "pt_beowulf_warband"),
			(neq, ":num_parties_destroyed_by_player_beowulf_warband", "$qst_cheese_rustlers_eliminated_by_player")
		],

		[
			(call_script, "script_end_quest", "qst_beowulf_quest4"),
			(setup_quest_text, "qst_beowulf_quest5"),
			(str_store_string, 2, "@Head to Duskendale to search for the horn."),
			(call_script, "script_start_quest", "qst_beowulf_quest5", "trp_beowulf_npc_5")
		]),

	(0.3, 0.0, 1.1,
		[
			(check_quest_active, "qst_ramsay_quest1"),
			(store_num_parties_destroyed, ":num_parties_destroyed_new_template", "pt_new_template"),
			(lt, "$qst_cheese_rustlers_eliminated", ":num_parties_destroyed_new_template"),
			(store_num_parties_destroyed_by_player, ":num_parties_destroyed_by_player_new_template", "pt_new_template"),
			(neq, ":num_parties_destroyed_by_player_new_template", "$qst_cheese_rustlers_eliminated_by_player")
		],

		[
			(call_script, "script_end_quest", "qst_ramsay_quest1"),
			(setup_quest_text, "qst_ramsay_quest2"),
			(str_store_string, 2, "@Return to Ser Rodrik Cassel and claim your reward."),
			(call_script, "script_start_quest", "qst_ramsay_quest2", "trp_rodrik_cassel_2")
		]),

	(0.3, 0.0, 1.1,
		[
			(check_quest_active, "qst_wildfire_quest4"),
			(store_num_parties_destroyed, ":num_parties_destroyed_wildfire_wights", "pt_wildfire_wights"),
			(lt, "$qst_cheese_rustlers_eliminated", ":num_parties_destroyed_wildfire_wights"),
			(store_num_parties_destroyed_by_player, ":num_parties_destroyed_by_player_wildfire_wights", "pt_wildfire_wights"),
			(neq, ":num_parties_destroyed_by_player_wildfire_wights", "$qst_cheese_rustlers_eliminated_by_player")
		],

		[
			(call_script, "script_end_quest", "qst_wildfire_quest4"),
			(setup_quest_text, "qst_wildfire_quest5"),
			(str_store_string, 2, "@Return to Gerold in White Harbor."),
			(call_script, "script_start_quest", "qst_wildfire_quest5", "trp_wildfire_npc_1")
		]),

	(0.3, 0.0, 1.1,
		[
			(check_quest_active, "qst_clansman_quest5"),
			(store_num_parties_destroyed, ":num_parties_destroyed_clansman_quest", "pt_clansman_quest"),
			(lt, "$qst_cheese_rustlers_eliminated", ":num_parties_destroyed_clansman_quest"),
			(store_num_parties_destroyed_by_player, ":num_parties_destroyed_by_player_clansman_quest", "pt_clansman_quest"),
			(neq, ":num_parties_destroyed_by_player_clansman_quest", "$qst_cheese_rustlers_eliminated_by_player")
		],

		[
			(call_script, "script_end_quest", "qst_clansman_quest5"),
			(setup_quest_text, "qst_clansman_quest6"),
			(str_store_string, 2, "@Return to Lysa Tully and claim your reward."),
			(call_script, "script_start_quest", "qst_clansman_quest6", "trp_clansman_npc_7")
		]),

	(0.3, 0.0, 1.1,
		[
			(check_quest_active, "qst_cheese_rustlers"),
			(neg|check_quest_failed, "qst_cheese_rustlers"),
			(store_num_parties_destroyed, ":num_parties_destroyed_cheese_rustlers", "pt_cheese_rustlers"),
			(lt, "$qst_cheese_rustlers_eliminated", ":num_parties_destroyed_cheese_rustlers"),
			(store_num_parties_destroyed_by_player, ":num_parties_destroyed_by_player_cheese_rustlers", "pt_cheese_rustlers"),
			(eq, ":num_parties_destroyed_by_player_cheese_rustlers", "$qst_cheese_rustlers_eliminated_by_player")
		],

		[
			(display_message, "str_cheese_rustlers_eliminated_by_another"),
			(call_script, "script_abort_quest", "qst_cheese_rustlers", 2)
		]),

	(0.3, 0.0, 1.1,
		[
			(check_quest_active, "qst_cheese_rustlers"),
			(neg|check_quest_succeeded, "qst_cheese_rustlers"),
			(store_num_parties_destroyed, ":num_parties_destroyed_cheese_rustlers", "pt_cheese_rustlers"),
			(lt, "$qst_cheese_rustlers_eliminated", ":num_parties_destroyed_cheese_rustlers"),
			(store_num_parties_destroyed_by_player, ":num_parties_destroyed_by_player_cheese_rustlers", "pt_cheese_rustlers"),
			(neq, ":num_parties_destroyed_by_player_cheese_rustlers", "$qst_cheese_rustlers_eliminated_by_player")
		],

		[
			(call_script, "script_succeed_quest", "qst_cheese_rustlers")
		]),

	(0.3, 0.0, 1.1,
		[
			(check_quest_active, "qst_cheese_paladins"),
			(neg|check_quest_failed, "qst_cheese_paladins"),
			(store_num_parties_destroyed, ":num_parties_destroyed_cheese_paladins", "pt_cheese_paladins"),
			(lt, "$qst_cheese_paladins_eliminated", ":num_parties_destroyed_cheese_paladins"),
			(store_num_parties_destroyed_by_player, ":num_parties_destroyed_by_player_cheese_paladins", "pt_cheese_paladins"),
			(eq, ":num_parties_destroyed_by_player_cheese_paladins", "$qst_cheese_paladins_eliminated_by_player")
		],

		[
			(display_message, "str_cheese_rustlers_eliminated_by_another"),
			(call_script, "script_abort_quest", "qst_cheese_paladins", 2)
		]),

	(0.3, 0.0, 1.1,
		[
			(check_quest_active, "qst_cheese_paladins"),
			(neg|check_quest_succeeded, "qst_cheese_paladins"),
			(store_num_parties_destroyed, ":num_parties_destroyed_cheese_paladins", "pt_cheese_paladins"),
			(lt, "$qst_cheese_paladins_eliminated", ":num_parties_destroyed_cheese_paladins"),
			(store_num_parties_destroyed_by_player, ":num_parties_destroyed_by_player_cheese_paladins", "pt_cheese_paladins"),
			(neq, ":num_parties_destroyed_by_player_cheese_paladins", "$qst_cheese_paladins_eliminated_by_player")
		],

		[
			(call_script, "script_succeed_quest", "qst_cheese_paladins")
		]),

	(0.1, 0.0, 0.1,
		[
			(check_quest_active, "qst_escort_scholars"),
			(eq, "$escort_scholars_mode", 1)
		],

		[
			(quest_get_slot, ":escort_scholars_target_party", "qst_escort_scholars", slot_quest_target_party),
			(try_begin),
				(party_is_active, ":escort_scholars_target_party"),
				(party_set_ai_behavior, ":escort_scholars_target_party", 0),
				(party_set_flags, ":escort_scholars_target_party", 65536, 0),
			(try_end)
		]),

	(0.1, 0.0, 0.1,
		[
			(check_quest_active, "qst_escort_scholars"),
			(eq, "$escort_scholars_mode", 0)
		],

		[
			(quest_get_slot, ":escort_scholars_target_party", "qst_escort_scholars", slot_quest_target_party),
			(try_begin),
				(party_is_active, ":escort_scholars_target_party"),
				(party_set_ai_behavior, ":escort_scholars_target_party", 10),
				(party_set_flags, ":escort_scholars_target_party", 65536, 0),
				(party_set_ai_object, ":escort_scholars_target_party", "p_main_party"),
			(try_end)
		]),

	(0.1, 0.0, 0.0,
		[
			(check_quest_active, "qst_escort_scholars"),
			(quest_get_slot, ":escort_scholars_target_party", "qst_escort_scholars", slot_quest_target_party),
			(neg|party_is_active, ":escort_scholars_target_party")
		],

		[
			(call_script, "script_abort_quest", "qst_escort_scholars", 2)
		]),

	(1.0, 0.0, 0.0,
		[
			(check_quest_active, "qst_kidnapped_wife"),
			(quest_get_slot, ":kidnapped_wife_target_party", "qst_kidnapped_wife", slot_quest_target_party),
			(party_is_active, ":kidnapped_wife_target_party"),
			(party_is_in_any_town, ":kidnapped_wife_target_party"),
			(remove_party, ":kidnapped_wife_target_party")
		],

		[]),

	(1.0, 0.0, 0.0,
		[
			(check_quest_active, "qst_kidnapped_girl"),
			(quest_get_slot, ":kidnapped_girl_target_party", "qst_kidnapped_girl", slot_quest_target_party),
			(party_is_active, ":kidnapped_girl_target_party"),
			(party_is_in_any_town, ":kidnapped_girl_target_party"),
			(remove_party, ":kidnapped_girl_target_party")
		],

		[]),

	(0.0, 0.0, 336.0,
		[
			(try_for_range, ":troop", "trp_kingdom_1_pretender", "trp_knight_1_1_wife"),
				(troop_set_slot, ":troop", slot_troop_cur_center, 0),
				(neq, ":troop", "$supported_pretender"),
				(troop_get_slot, ":troop_original_faction", ":troop", slot_troop_original_faction),
				(faction_slot_eq, ":troop_original_faction", slot_faction_state, 0),
				(faction_slot_eq, ":troop_original_faction", slot_faction_instability, 1),
				(neg|troop_slot_eq, ":troop", slot_troop_occupation, 2),
				(try_for_range, ":unused", 0, 30),
					(troop_slot_eq, ":troop", slot_troop_cur_center, 0),
					(store_random_in_range, ":random_in_range_town_1_castle_1", "p_town_1", "p_castle_1"),
					(store_faction_of_party, ":faction_of_party_random_in_range_town_1_castle_1", ":random_in_range_town_1_castle_1"),
					(store_relation, ":relation_faction_of_party_random_in_range_town_1_castle_1_troop_original_faction", ":faction_of_party_random_in_range_town_1_castle_1", ":troop_original_faction"),
					(le, ":relation_faction_of_party_random_in_range_town_1_castle_1_troop_original_faction", 0),
					(troop_set_slot, ":troop", slot_troop_cur_center, ":random_in_range_town_1_castle_1"),
					(try_begin),
						(eq, "$cheat_mode", 1),
						(str_store_troop_name, 4, ":troop"),
						(str_store_party_name, 5, ":random_in_range_town_1_castle_1"),
						(display_message, "@{!}{s4} is in {s5}"),
					(try_end),
				(try_end),
			(try_end)
		],

		[]),

	(360.0, 0.0, 0.0,
		[
			(call_script, "script_update_companion_candidates_in_taverns")
		],

		[]),

	(0.0, 0.0, 24.0,
		[],

		[
			(assign, ":var_1", 0),
			(assign, ":var_2", 100),
			(try_for_range, ":troop", "trp_npc1", "trp_kingdom_1_lord"),
				(main_party_has_troop, ":troop"),
				(val_add, ":var_1", 1),
			(try_end),
			(val_sub, ":var_2", ":var_1"),
			(store_skill_level, ":skill_level_persuasion_player", "skl_persuasion", "trp_player"),
			(val_add, ":var_2", ":skill_level_persuasion_player"),
			(assign, reg7, ":var_2"),
			(try_begin),
				(gt, "$personality_clash_after_24_hrs", 0),
				(eq, "$disable_npc_complaints", 0),
				(try_begin),
					(troop_get_slot, ":personality_clash_after_24_hrs_personalityclash_object", "$personality_clash_after_24_hrs", slot_troop_personalityclash_object),
					(main_party_has_troop, "$personality_clash_after_24_hrs"),
					(main_party_has_troop, ":personality_clash_after_24_hrs_personalityclash_object"),
					(assign, "$npc_with_personality_clash", "$personality_clash_after_24_hrs"),
				(try_end),
				(assign, "$personality_clash_after_24_hrs", 0),
			(try_end),
			(try_for_range, ":troop_2", "trp_npc1", "trp_kingdom_1_lord"),
				(troop_set_slot, ":troop_2", slot_troop_turned_down_twice, 0),
				(try_begin),
					(troop_slot_eq, ":troop_2", slot_troop_met, 1),
					(troop_set_slot, ":troop_2", slot_troop_met_previously, 1),
				(try_end),
				(troop_get_slot, ":troop_2_occupation", ":troop_2", slot_troop_occupation),
				(try_begin),
					(eq, ":troop_2_occupation", 11),
					(troop_get_slot, ":troop_2_return_renown", ":troop_2", slot_troop_return_renown),
					(str_store_troop_name, 31, ":troop_2"),
					(troop_get_slot, ":player_renown", "trp_player", slot_troop_renown),
					(assign, reg4, ":player_renown"),
					(assign, reg5, ":troop_2_return_renown"),
					(gt, ":player_renown", ":troop_2_return_renown"),
					(troop_set_slot, ":troop_2", slot_troop_personalityclash_penalties, 0),
					(troop_set_slot, ":troop_2", slot_troop_morality_penalties, 0),
					(troop_set_slot, ":troop_2", slot_troop_occupation, 0),
				(try_end),
				(try_begin),
					(troop_slot_ge, ":troop_2", 150, 5),
					(troop_slot_eq, ":troop_2", slot_troop_current_mission, 1),
					(troop_get_slot, ":personality_clash_after_24_hrs_personalityclash_object", ":troop_2", slot_troop_kingsupport_opponent),
					(troop_slot_eq, ":personality_clash_after_24_hrs_personalityclash_object", slot_troop_kingsupport_objection_state, 0),
					(troop_set_slot, ":personality_clash_after_24_hrs_personalityclash_object", slot_troop_kingsupport_objection_state, 1),
					(str_store_troop_name, 3, ":troop_2"),
					(str_store_troop_name, 4, ":personality_clash_after_24_hrs_personalityclash_object"),
					(try_begin),
						(eq, "$cheat_mode", 1),
						(display_message, "str_s4_ready_to_voice_objection_to_s3s_mission_if_in_party"),
					(try_end),
				(try_end),
				(try_begin),
					(main_party_has_troop, ":troop_2"),
					(call_script, "script_npc_morale", ":troop_2"),
					(assign, ":var_10", reg0),
					(try_begin),
						(lt, ":var_10", 20),
						(store_random_in_range, ":random_in_range_0_100", 0, 100),
						(val_add, ":var_10", ":random_in_range_0_100"),
						(lt, ":var_10", 20),
						(assign, "$npc_is_quitting", ":troop_2"),
					(try_end),
					(troop_get_slot, ":troop_2_personalityclash_penalties", ":troop_2", slot_troop_personalityclash_penalties),
					(val_mul, ":troop_2_personalityclash_penalties", 90),
					(val_div, ":troop_2_personalityclash_penalties", ":var_2"),
					(troop_set_slot, ":troop_2", slot_troop_personalityclash_penalties, ":troop_2_personalityclash_penalties"),
					(troop_get_slot, ":troop_2_personalityclash_penalties", ":troop_2", slot_troop_morality_penalties),
					(val_mul, ":troop_2_personalityclash_penalties", 90),
					(val_div, ":troop_2_personalityclash_penalties", ":var_2"),
					(troop_set_slot, ":troop_2", slot_troop_morality_penalties, ":troop_2_personalityclash_penalties"),
					(try_begin),
						(this_or_next|troop_slot_ge, ":troop_2", 72, 1),
						(eq, "$disable_npc_complaints", 1),
						(troop_get_slot, ":troop_2_personalityclash_object", ":troop_2", slot_troop_personalityclash_object),
						(main_party_has_troop, ":troop_2_personalityclash_object"),
						(call_script, "script_reduce_companion_morale_for_clash", ":troop_2", ":troop_2_personalityclash_object", 72),
					(try_end),
					(try_begin),
						(this_or_next|troop_slot_ge, ":troop_2", 74, 1),
						(eq, "$disable_npc_complaints", 1),
						(troop_get_slot, ":troop_2_personalityclash_object", ":troop_2", slot_troop_personalityclash2_object),
						(main_party_has_troop, ":troop_2_personalityclash_object"),
						(call_script, "script_reduce_companion_morale_for_clash", ":troop_2", ":troop_2_personalityclash_object", 74),
					(try_end),
					(try_begin),
						(this_or_next|troop_slot_ge, ":troop_2", 76, 1),
						(eq, "$disable_npc_complaints", 1),
						(troop_get_slot, ":troop_2_personalityclash_object", ":troop_2", slot_troop_personalitymatch_object),
						(main_party_has_troop, ":troop_2_personalityclash_object"),
						(troop_get_slot, ":troop_2_personalityclash_penalties", ":troop_2", slot_troop_personalityclash_penalties),
						(val_mul, ":troop_2_personalityclash_penalties", 9),
						(val_div, ":troop_2_personalityclash_penalties", 10),
						(troop_set_slot, ":troop_2", slot_troop_personalityclash_penalties, ":troop_2_personalityclash_penalties"),
					(try_end),
					(try_begin),
						(eq, "$disable_npc_complaints", 0),
						(eq, "$npc_with_personality_clash", 0),
						(eq, "$npc_with_personality_clash_2", 0),
						(eq, "$personality_clash_after_24_hrs", 0),
						(troop_slot_eq, ":troop_2", slot_troop_personalityclash_state, 0),
						(troop_get_slot, ":personality_clash_after_24_hrs_personalityclash_object", ":troop_2", slot_troop_personalityclash_object),
						(main_party_has_troop, ":personality_clash_after_24_hrs_personalityclash_object"),
						(assign, "$personality_clash_after_24_hrs", ":troop_2"),
					(try_end),
					(try_begin),
						(eq, "$npc_with_political_grievance", 0),
						(troop_slot_eq, ":troop_2", slot_troop_kingsupport_objection_state, 1),
						(assign, "$npc_with_political_grievance", ":troop_2"),
					(try_end),
				(else_try),
					(neg|main_party_has_troop, ":troop_2"),
					(eq, ":troop_2_occupation", 5),
					(troop_get_slot, ":troop_2_days_on_mission", ":troop_2", slot_troop_days_on_mission),
					(try_begin),
						(eq, "$cheat_mode", 1),
						(str_store_troop_name, 10, ":troop_2"),
						(assign, reg0, ":troop_2_days_on_mission"),
						(display_message, "@Checking rejoin of {s10} days on mission: {reg0}"),
					(try_end),
					(try_begin),
						(gt, ":troop_2_days_on_mission", 0),
						(val_sub, ":troop_2_days_on_mission", 1),
						(troop_set_slot, ":troop_2", slot_troop_days_on_mission, ":troop_2_days_on_mission"),
					(else_try),
						(troop_slot_eq, ":troop_2", slot_troop_current_mission, 11),
						(troop_slot_ge, ":troop_2", 162, 1),
						(troop_get_slot, ":troop_trees_608", "$troop_trees", 608),
						(troop_set_slot, ":troop_trees_608", slot_troop_mission_object, ":troop_2"),
						(assign, "$npc_to_rejoin_party", ":troop_trees_608"),
					(else_try),
						(troop_slot_ge, ":troop_2", 151, 1),
						(this_or_next|neg|troop_slot_eq, ":troop_2", slot_troop_current_mission, 8),
						(hero_can_join),
						(assign, "$npc_to_rejoin_party", ":troop_2"),
					(try_end),
				(try_end),
			(try_end)
		]),

	(1.0, 0.0, 0.0,
		[
			(troop_get_type, ":type_player", "trp_player"),
			(eq, ":type_player", 1),
			(try_for_range, ":troop", "trp_npc1", "trp_kingdom_1_lord"),
				(troop_slot_eq, ":troop", slot_troop_occupation, 5),
				(troop_get_inventory_capacity, ":inventory_capacity_troop", ":troop"),
				(try_for_range, ":number", 0, ":inventory_capacity_troop"),
					(troop_get_inventory_slot, ":inventory_slot_troop_number", ":troop", ":number"),
					(ge, ":inventory_slot_troop_number", 0),
					(this_or_next|eq, ":inventory_slot_troop_number", "itm_we_swa_sword_twohanded_claymore"),
					(this_or_next|eq, ":inventory_slot_troop_number", "itm_we_swa_sword_clamshell_claymore"),
					(this_or_next|eq, ":inventory_slot_troop_number", "itm_we_pla_sword_great_four"),
					(eq, ":inventory_slot_troop_number", "itm_we_pla_sword_great_four"),
					(unlock_achievement, 80),
					(assign, ":inventory_capacity_troop", 0),
				(try_end),
			(try_end)
		],

		[]),

	(24.0, 0.0, 288.0,
		[],

		[
			(assign, ":value", 0),
			(try_for_range, ":party", "p_town_1", "p_salt_mine"),
				(party_get_slot, ":party_town_lord", ":party", slot_town_lord),
				(eq, ":party_town_lord", "trp_player"),
				(assign, ":value", 1),
			(try_end),
			(eq, ":value", 1),
			(try_begin),
				(eq, "$cheat_mode", 1),
				(assign, reg0, "$g_player_chamberlain"),
				(display_message, "@{!}DEBUG : chamberlain: {reg0}"),
			(try_end),
			(assign, ":value_2", 0),
			(try_begin),
				(eq, "$g_player_chamberlain", 0),
				(assign, ":value_2", 1),
			(else_try),
				(neq, "$g_player_chamberlain", -1),
				(neq, "$g_player_chamberlain", "trp_dplmc_chamberlain"),
				(assign, ":value_2", 1),
			(try_end),
			(try_begin),
				(eq, ":value_2", 1),
				(call_script, "script_add_notification_menu", "mnu_dplmc_notification_appoint_chamberlain", 0, 0),
			(try_end)
		]),

	(24.0, 0.0, 312.0,
		[],

		[
			(assign, ":value", 0),
			(try_for_range, ":party", "p_town_1", "p_village_1"),
				(party_get_slot, ":party_town_lord", ":party", slot_town_lord),
				(eq, ":party_town_lord", "trp_player"),
				(assign, ":value", 1),
			(try_end),
			(eq, ":value", 1),
			(try_begin),
				(eq, "$cheat_mode", 1),
				(assign, reg0, "$g_player_constable"),
				(display_message, "@{!}DEBUG : constable: {reg0}"),
			(try_end),
			(assign, ":value_2", 0),
			(try_begin),
				(eq, "$g_player_constable", 0),
				(assign, ":value_2", 1),
			(else_try),
				(neq, "$g_player_constable", -1),
				(neq, "$g_player_constable", "trp_dplmc_constable"),
				(assign, ":value_2", 1),
			(try_end),
			(try_begin),
				(eq, ":value_2", 1),
				(call_script, "script_add_notification_menu", "mnu_dplmc_notification_appoint_constable", 0, 0),
			(try_end)
		]),

	(24.0, 0.0, 336.0,
		[],

		[
			(assign, ":value", 0),
			(try_for_range, ":party", "p_town_1", "p_castle_1"),
				(party_get_slot, ":party_town_lord", ":party", slot_town_lord),
				(eq, ":party_town_lord", "trp_player"),
				(assign, ":value", 1),
			(try_end),
			(eq, ":value", 1),
			(try_begin),
				(eq, "$cheat_mode", 1),
				(assign, reg0, "$g_player_chancellor"),
				(display_message, "@{!}DEBUG : chancellor: {reg0}"),
			(try_end),
			(assign, ":value_2", 0),
			(try_begin),
				(eq, "$g_player_chancellor", 0),
				(assign, ":value_2", 1),
			(else_try),
				(neq, "$g_player_chancellor", -1),
				(neq, "$g_player_chancellor", "trp_dplmc_chancellor"),
				(assign, ":value_2", 1),
			(try_end),
			(try_begin),
				(eq, ":value_2", 1),
				(call_script, "script_add_notification_menu", "mnu_dplmc_notification_appoint_chancellor", 0, 0),
			(try_end)
		]),

	(0.1, 0.5, 0.0,
		[
			(map_free, 0),
			(eq, "$g_move_fast", 1)
		],

		[
			(assign, "$g_move_fast", 0)
		]),

	(50.0, 0.0, 0.0,
		[],

		[
			(try_for_range, ":party", "p_town_1", "p_village_1"),
				(party_get_slot, ":party_center_is_besieged_by", ":party", slot_center_is_besieged_by),
				(lt, ":party_center_is_besieged_by", 0),
				(store_faction_of_party, ":faction_of_party_party", ":party"),
				(party_get_num_companions, ":num_companions_party", ":party"),
				(faction_get_slot, ":faction_of_party_party_reinforcements_a", ":faction_of_party_party", slot_faction_reinforcements_a),
				(faction_get_slot, ":faction_of_party_party_reinforcements_c", ":faction_of_party_party", slot_faction_reinforcements_c),
				(faction_get_slot, ":faction_of_party_party_106", ":faction_of_party_party", 106),
				(faction_get_slot, ":faction_of_party_party_107", ":faction_of_party_party", 107),
				(faction_get_slot, ":faction_of_party_party_108", ":faction_of_party_party", 108),
				(assign, ":value", 0),
				(try_begin),
					(party_slot_eq, ":party", slot_party_type, 3),
					(lt, ":num_companions_party", 200),
					(assign, ":value", "pt_reinforcements"),
				(else_try),
					(party_slot_eq, ":party", slot_party_type, 2),
					(lt, ":num_companions_party", 70),
					(assign, ":value", "pt_reinforcements"),
				(try_end),
				(try_begin),
					(gt, ":value", 0),
					(try_for_range, ":party_2", "p_village_1", "p_salt_mine"),
						(try_begin),
							(party_slot_eq, ":party", slot_party_type, 2),
							(party_slot_eq, ":party_2", slot_village_bound_center, ":party"),
							(party_slot_eq, ":party_2", slot_village_state, 0),
							(neg|party_slot_eq, ":party", slot_town_lord, "trp_player"),
							(spawn_around_party, ":party_2", ":value"),
							(assign, ":value_2", reg0),
							(store_random_in_range, ":random_in_range_0_100", 0, 100),
							(try_begin),
								(is_between, ":random_in_range_0_100", 0, 45),
								(party_add_template, ":value_2", ":faction_of_party_party_reinforcements_a"),
							(else_try),
								(is_between, ":random_in_range_0_100", 45, 60),
								(party_add_template, ":value_2", ":faction_of_party_party_reinforcements_c"),
							(else_try),
								(is_between, ":random_in_range_0_100", 60, 75),
								(party_add_template, ":value_2", ":faction_of_party_party_106"),
							(else_try),
								(is_between, ":random_in_range_0_100", 75, 85),
								(party_add_template, ":value_2", ":faction_of_party_party_107"),
							(else_try),
								(ge, ":random_in_range_0_100", 85),
								(party_add_template, ":value_2", ":faction_of_party_party_108"),
							(try_end),
							(party_set_faction, ":value_2", ":faction_of_party_party"),
							(party_set_slot, ":value_2", slot_party_type, 23),
							(party_set_slot, ":value_2", slot_party_ai_object, ":party"),
							(str_store_party_name, 14, ":party_2"),
							(party_set_name, ":value_2", "@Reinforcements from {s14}"),
							(party_set_ai_behavior, ":value_2", 1),
							(party_set_ai_object, ":value_2", ":party"),
							(party_set_flags, ":value_2", 65536, 1),
						(else_try),
							(party_slot_eq, ":party", slot_party_type, 3),
							(party_slot_eq, ":party_2", slot_village_bound_center, ":party"),
							(party_slot_eq, ":party_2", slot_village_state, 0),
							(neg|party_slot_eq, ":party", slot_town_lord, "trp_player"),
							(spawn_around_party, ":party_2", ":value"),
							(assign, ":value_2", reg0),
							(store_random_in_range, ":random_in_range_0_100", 0, 100),
							(try_begin),
								(is_between, ":random_in_range_0_100", 0, 45),
								(party_add_template, ":value_2", ":faction_of_party_party_reinforcements_a"),
							(else_try),
								(is_between, ":random_in_range_0_100", 45, 60),
								(party_add_template, ":value_2", ":faction_of_party_party_reinforcements_c"),
							(else_try),
								(is_between, ":random_in_range_0_100", 60, 75),
								(party_add_template, ":value_2", ":faction_of_party_party_106"),
							(else_try),
								(is_between, ":random_in_range_0_100", 75, 85),
								(party_add_template, ":value_2", ":faction_of_party_party_107"),
							(else_try),
								(ge, ":random_in_range_0_100", 85),
								(party_add_template, ":value_2", ":faction_of_party_party_108"),
							(try_end),
							(party_set_faction, ":value_2", ":faction_of_party_party"),
							(party_set_slot, ":value_2", slot_party_type, 23),
							(party_set_slot, ":value_2", slot_party_ai_object, ":party"),
							(str_store_party_name, 14, ":party_2"),
							(party_set_name, ":value_2", "@Reinforcements from {s14}"),
							(party_set_ai_behavior, ":value_2", 1),
							(party_set_ai_object, ":value_2", ":party"),
							(party_set_flags, ":value_2", 65536, 1),
						(try_end),
					(try_end),
				(try_end),
			(try_end)
		]),

	(0.1, 0.0, 0.0,
		[
			(party_get_current_terrain, ":current_terrain_main_party", "p_main_party"),
			(neq, ":current_terrain_main_party", 15)
		],

		[
			(troop_get_inventory_slot, ":inventory_slot_player_8", "trp_player", 8),
			(assign, ":value", -1),
			(try_begin),
				(eq, "$g_player_icon_state", 0),
				(try_begin),
					(ge, ":inventory_slot_player_8", 0),
					(assign, ":value", "icon_people_player_horseman"),
				(else_try),
					(assign, ":value", "icon_people_player"),
				(try_end),
				(party_set_icon, "p_main_party", ":value"),
			(else_try),
				(eq, "$g_player_icon_state", 1),
				(assign, ":value", "icon_camp_tent"),
				(party_set_icon, "p_main_party", ":value"),
			(try_end)
		]),

	(0.1, 0.0, 0.0,
		[
			(party_get_current_terrain, ":current_terrain_main_party", "p_main_party"),
			(eq, ":current_terrain_main_party", 15)
		],

		[
			(party_set_icon, "p_main_party", "icon_ship")
		]),

	(0.1, 0.0, 0.0,
		[],

		[
			(try_for_parties, ":var_1"),
				(party_get_current_terrain, ":current_terrain_var_1", ":var_1"),
				(eq, ":current_terrain_var_1", 15),
				(party_get_template_id, ":template_id_var_1", ":var_1"),
				(this_or_next|eq, ":template_id_var_1", "pt_kingdom_hero_party"),
				(this_or_next|eq, ":template_id_var_1", "pt_kingdom_caravan_party"),
				(this_or_next|eq, ":template_id_var_1", "pt_kingdom_caravan_party_r"),
				(this_or_next|eq, ":template_id_var_1", "pt_kingdom_caravan_party_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_center_reinforcements_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_manhunters_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_village_farmers_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_taiga_bandits_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_deserters"),
				(this_or_next|eq, ":template_id_var_1", "pt_looters_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_forest_bandits_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_steppe_bandits_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_mountain_bandits_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_desert_bandits_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_slaver"),
				(this_or_next|eq, ":template_id_var_1", "pt_escaped_slaves"),
				(this_or_next|eq, ":template_id_var_1", "pt_clansmen"),
				(this_or_next|eq, ":template_id_var_1", "pt_raiders"),
				(this_or_next|eq, ":template_id_var_1", "pt_outlaws"),
				(this_or_next|eq, ":template_id_var_1", "pt_rhoyne_outlaws"),
				(this_or_next|eq, ":template_id_var_1", "pt_crannogmen"),
				(this_or_next|eq, ":template_id_var_1", "pt_elite_raiders"),
				(this_or_next|eq, ":template_id_var_1", "pt_elite_wildlings"),
				(this_or_next|eq, ":template_id_var_1", "pt_elite_dothraki"),
				(this_or_next|eq, ":template_id_var_1", "pt_patrol_party"),
				(this_or_next|eq, ":template_id_var_1", "pt_scout_party"),
				(this_or_next|eq, ":template_id_var_1", "pt_forager_party"),
				(this_or_next|eq, ":template_id_var_1", "pt_messenger_party"),
				(this_or_next|eq, ":template_id_var_1", "pt_raider_party"),
				(this_or_next|eq, ":template_id_var_1", "pt_spy"),
				(this_or_next|eq, ":template_id_var_1", "pt_merchant_caravan"),
				(this_or_next|eq, ":template_id_var_1", "pt_merchant_caravan_r"),
				(this_or_next|eq, ":template_id_var_1", "pt_merchant_caravan_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_troublesome_bandits"),
				(this_or_next|eq, ":template_id_var_1", "pt_troublesome_bandits_r"),
				(this_or_next|eq, ":template_id_var_1", "pt_troublesome_bandits_e"),
				(eq, ":template_id_var_1", "pt_sea_raiders_e"),
				(party_set_icon, ":var_1", "icon_ship"),
			(else_try),
				(neq, ":current_terrain_var_1", 15),
				(party_get_template_id, ":template_id_var_1", ":var_1"),
				(eq, ":template_id_var_1", "pt_kingdom_hero_party"),
				(party_set_icon, ":var_1", "icon_people_flagbearer_a"),
			(else_try),
				(this_or_next|eq, ":template_id_var_1", "pt_merchant_caravan"),
				(this_or_next|eq, ":template_id_var_1", "pt_merchant_caravan_r"),
				(this_or_next|eq, ":template_id_var_1", "pt_merchant_caravan_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_kingdom_caravan_party"),
				(this_or_next|eq, ":template_id_var_1", "pt_kingdom_caravan_party_r"),
				(this_or_next|eq, ":template_id_var_1", "pt_kingdom_caravan_party_e"),
				(eq, ":template_id_var_1", "pt_center_reinforcements_e"),
				(party_set_icon, ":var_1", "icon_people_mule"),
			(else_try),
				(this_or_next|eq, ":template_id_var_1", "pt_desert_bandits_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_outlaws"),
				(this_or_next|eq, ":template_id_var_1", "pt_beowulf_warband"),
				(this_or_next|eq, ":template_id_var_1", "pt_wildfire_wights"),
				(this_or_next|eq, ":template_id_var_1", "pt_new_template"),
				(this_or_next|eq, ":template_id_var_1", "pt_clansman_quest"),
				(this_or_next|eq, ":template_id_var_1", "pt_routed_warriors"),
				(eq, ":template_id_var_1", "pt_routed_warriors"),
				(party_set_icon, ":var_1", "icon_people_vaegir_knight"),
			(else_try),
				(this_or_next|eq, ":template_id_var_1", "pt_rescued_prisoners"),
				(this_or_next|eq, ":template_id_var_1", "pt_manhunters_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_spy_partners_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_spy"),
				(this_or_next|eq, ":template_id_var_1", "pt_sacrificed_messenger"),
				(this_or_next|eq, ":template_id_var_1", "pt_forager_party"),
				(this_or_next|eq, ":template_id_var_1", "pt_scout_party"),
				(this_or_next|eq, ":template_id_var_1", "pt_patrol_party"),
				(this_or_next|eq, ":template_id_var_1", "pt_messenger_party"),
				(this_or_next|eq, ":template_id_var_1", "pt_raider_party"),
				(this_or_next|eq, ":template_id_var_1", "pt_prisoner_train_party"),
				(eq, ":template_id_var_1", "pt_dplmc_recruiter"),
				(party_set_icon, ":var_1", "icon_people_gray_knight"),
			(else_try),
				(this_or_next|eq, ":template_id_var_1", "pt_village_defenders_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_escaped_slaves"),
				(this_or_next|eq, ":template_id_var_1", "pt_scholars"),
				(this_or_next|eq, ":template_id_var_1", "pt_kidnapped_wife"),
				(this_or_next|eq, ":template_id_var_1", "pt_village_farmers_e"),
				(eq, ":template_id_var_1", "pt_runaway_serfs_e"),
				(party_set_icon, ":var_1", "icon_people_peasant"),
			(else_try),
				(this_or_next|eq, ":template_id_var_1", "pt_nemesis"),
				(this_or_next|eq, ":template_id_var_1", "pt_nemesis2"),
				(this_or_next|eq, ":template_id_var_1", "pt_looters_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_arrians"),
				(this_or_next|eq, ":template_id_var_1", "pt_troublesome_bandits_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_bandits_awaiting_ransom_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_center_reinforcements_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_bandit_lair_templates_end_e"),
				(this_or_next|eq, ":template_id_var_1", "pt_slaver"),
				(this_or_next|eq, ":template_id_var_1", "pt_elite_raiders"),
				(this_or_next|eq, ":template_id_var_1", "pt_elite_wildlings"),
				(this_or_next|eq, ":template_id_var_1", "pt_elite_dothraki"),
				(eq, ":template_id_var_1", "pt_reinforcements"),
				(party_set_icon, ":var_1", "icon_people_axeman"),
			(else_try),
				(this_or_next|eq, ":template_id_var_1", "pt_kidnapped_girl"),
				(eq, ":template_id_var_1", "pt_dplmc_spouse"),
				(party_set_icon, ":var_1", "icon_people_woman"),
			(else_try),
				(eq, ":template_id_var_1", "pt_deserters"),
				(party_set_icon, ":var_1", "icon_new_icon_deserters"),
			(else_try),
				(this_or_next|eq, ":template_id_var_1", "pt_taiga_bandits_e"),
				(eq, ":template_id_var_1", "pt_clansmen"),
				(party_set_icon, ":var_1", "icon_new_icon_wildlings"),
			(else_try),
				(eq, ":template_id_var_1", "pt_mountain_bandits_e"),
				(party_set_icon, ":var_1", "icon_new_icon_mountain_bandit"),
			(else_try),
				(eq, ":template_id_var_1", "pt_rhoyne_outlaws"),
				(party_set_icon, ":var_1", "icon_new_icon_rhoyne_outlaw"),
			(else_try),
				(eq, ":template_id_var_1", "pt_rhoyne_outlaws"),
				(party_set_icon, ":var_1", "icon_new_icon_rhoyne_outlaw"),
			(else_try),
				(eq, ":template_id_var_1", "pt_crannogmen"),
				(party_set_icon, ":var_1", "icon_new_icon_crannogmen"),
			(else_try),
				(this_or_next|eq, ":template_id_var_1", "pt_cheese_rustlers"),
				(this_or_next|eq, ":template_id_var_1", "pt_sea_raiders_e"),
				(eq, ":template_id_var_1", "pt_cheese_paladins"),
				(party_set_icon, ":var_1", "icon_new_icon_thieves"),
			(else_try),
				(this_or_next|eq, ":template_id_var_1", "pt_smugglers"),
				(eq, ":template_id_var_1", "pt_bandits_awaiting_ransom2"),
				(party_set_icon, ":var_1", "icon_new_icon_bandits"),
			(else_try),
				(eq, ":template_id_var_1", "pt_forest_bandits_e"),
				(party_set_icon, ":var_1", "icon_new_icon_forest_bandit"),
			(else_try),
				(eq, ":template_id_var_1", "pt_raiders"),
				(party_set_icon, ":var_1", "icon_new_icon_raiders"),
			(else_try),
				(eq, ":template_id_var_1", "pt_steppe_bandits_e"),
				(party_set_icon, ":var_1", "icon_new_icon_dothraki"),
				(eq, ":template_id_var_1", "pt_cattle_herd"),
				(party_set_icon, ":var_1", "icon_people_cattle"),
			(try_end)
		]),

	(0.0, 0.0, 0.0,
		[
			(eq, "$freelancer_state", 1),
			(gt, "$enlisted_party", 0),
			(neg|party_is_active, "$enlisted_party"),
			(check_quest_active, "qst_freelancer_enlisted")
		],

		[
			(call_script, "script_freelancer_event_player_captured"),
			(assign, "$g_encountered_party", "$g_enemy_party"),
			(jump_to_menu, "mnu_captivity_start_wilderness")
		]),

	(0.0, 0.0, 0.0,
		[
			(eq, "$freelancer_state", 1),
			(check_quest_active, "qst_freelancer_enlisted"),
			(try_begin),
				(party_slot_ge, "p_freelancer_party_backup", 68, 1),
				(map_free),
				(party_set_slot, "p_freelancer_party_backup", slot_party_last_in_combat, 0),
				(party_get_num_attached_parties, ":num_attached_parties_main_party", "p_main_party"),
				(try_for_range_backwards, ":var_2", 0, ":num_attached_parties_main_party"),
					(party_get_attached_party_with_rank, ":attached_party_with_rank_main_party_var_2", "p_main_party", ":var_2"),
					(party_detach, ":attached_party_with_rank_main_party_var_2"),
				(try_end),
			(try_end),
			(party_get_battle_opponent, ":battle_opponent_l_enlisted_party", "$enlisted_party"),
			(gt, ":battle_opponent_l_enlisted_party", 0),
			(store_troop_health, ":troop_health_player", "trp_player"),
			(ge, ":troop_health_player", 50)
		],

		[
			(jump_to_menu, "mnu_world_map_soldier")
		]),

	(1.0, 0.0, 0.0,
		[
			(check_quest_active, "qst_freelancer_revolt")
		],

		[
			(quest_get_slot, ":freelancer_revolt_target_party", "qst_freelancer_revolt", slot_quest_target_party),
			(try_begin),
				(quest_slot_eq, "qst_freelancer_revolt", slot_quest_current_state, 0),
				(try_begin),
					(neg|party_is_active, "$enlisted_party"),
					(try_begin),
						(gt, ":freelancer_revolt_target_party", 0),
						(party_is_active, ":freelancer_revolt_target_party"),
						(party_detach, ":freelancer_revolt_target_party"),
						(quest_set_slot, "qst_freelancer_revolt", slot_quest_current_state, 1),
					(else_try),
						(call_script, "script_finish_quest", "qst_freelancer_revolt", 100),
					(try_end),
				(else_try),
					(try_begin),
						(gt, ":freelancer_revolt_target_party", 0),
						(party_is_active, ":freelancer_revolt_target_party"),
						(party_detach, ":freelancer_revolt_target_party"),
						(remove_party, ":freelancer_revolt_target_party"),
					(try_end),
					(call_script, "script_fail_quest", "qst_freelancer_revolt"),
					(call_script, "script_end_quest", "qst_freelancer_revolt"),
				(try_end),
				(assign, "$enlisted_party", 0),
			(try_end),
			(quest_slot_ge, "qst_freelancer_revolt", 11, 1),
			(try_begin),
				(quest_slot_eq, "qst_freelancer_revolt", slot_quest_current_state, 1),
				(store_skill_level, ":skill_level_leadership_player", "skl_leadership", "trp_player"),
				(store_skill_level, ":skill_level_persuasion_player", "skl_persuasion", "trp_player"),
				(store_add, ":value", ":skill_level_persuasion_player", ":skill_level_leadership_player"),
				(val_add, ":value", 10),
				(store_random_in_range, ":random_in_range_0_value", 0, ":value"),
				(try_begin),
					(is_between, ":random_in_range_0_value", 0, 5),
					(call_script, "script_party_calculate_strength", "p_main_party", 0),
					(assign, ":var_6", reg0),
					(call_script, "script_party_calculate_strength", ":freelancer_revolt_target_party", 0),
					(assign, ":var_7", reg0),
					(ge, ":var_7", ":var_6"),
					(party_get_num_prisoner_stacks, ":num_prisoner_stacks_freelancer_revolt_target_party", ":freelancer_revolt_target_party"),
					(try_for_range, ":number", 0, ":num_prisoner_stacks_freelancer_revolt_target_party"),
						(party_prisoner_stack_get_troop_id, ":party_prisoner_stack_troop_id_freelancer_revolt_target_party_number", ":freelancer_revolt_target_party", ":number"),
						(party_prisoner_stack_get_size, ":party_prisoner_stack_size_freelancer_revolt_target_party_number", ":freelancer_revolt_target_party", ":number"),
						(party_remove_prisoners, ":freelancer_revolt_target_party", ":party_prisoner_stack_troop_id_freelancer_revolt_target_party_number", ":party_prisoner_stack_size_freelancer_revolt_target_party_number"),
					(try_end),
					(quest_set_slot, "qst_freelancer_revolt", slot_quest_current_state, 2),
					(dialog_box, "@The released prisoners were not be trusted and they are preparing to attack you!", "@Warning!"),
					(start_encounter, ":freelancer_revolt_target_party"),
					(change_screen_map),
				(else_try),
					(is_between, ":random_in_range_0_value", 5, 10),
					(dialog_box, "@The released prisoners scattered as soon as the battle finished. You will not be seeing them again.", "@Notice!"),
					(remove_party, ":freelancer_revolt_target_party"),
					(call_script, "script_finish_quest", "qst_freelancer_revolt", 100),
					(quest_set_slot, "qst_freelancer_revolt", slot_quest_current_state, 0),
				(else_try),
					(dialog_box, "@The released prisoners have remained loyal and will join your party", "@Notice!"),
					(call_script, "script_party_add_party", "p_main_party", ":freelancer_revolt_target_party"),
					(remove_party, ":freelancer_revolt_target_party"),
					(call_script, "script_finish_quest", "qst_freelancer_revolt", 100),
					(quest_set_slot, "qst_freelancer_revolt", slot_quest_current_state, 0),
				(try_end),
			(else_try),
				(quest_slot_eq, "qst_freelancer_revolt", slot_quest_current_state, 2),
				(try_begin),
					(neg|party_is_active, ":freelancer_revolt_target_party"),
					(neq, "$g_player_is_captive", 1),
					(call_script, "script_finish_quest", "qst_freelancer_revolt", 100),
				(else_try),
					(call_script, "script_fail_quest", "qst_freelancer_revolt"),
					(call_script, "script_end_quest", "qst_freelancer_revolt"),
				(try_end),
				(quest_set_slot, "qst_freelancer_revolt", slot_quest_current_state, 0),
			(try_end)
		]),

	(0.0, 0.0, 0.0,
		[
			(eq, "$freelancer_state", 1),
			(key_clicked, 224),
			(set_fixed_point_multiplier, 1000),
			(mouse_get_position, 0),
			(position_get_y, ":position_y_0", 0),
			(gt, ":position_y_0", 50)
		],

		[
			(jump_to_menu, "mnu_world_map_soldier"),
			(rest_for_hours_interactive, 9999, 4, 0)
		]),

	(24.0, 0.0, 0.0,
		[
			(eq, "$freelancer_state", 2)
		],

		[
			(try_for_range, ":quest", "qst_freelancer_enlisted", "qst_freelancer_end"),
				(check_quest_active, ":quest"),
				(quest_get_slot, ":quest_expiration_days", ":quest", slot_quest_expiration_days),
				(ge, ":quest_expiration_days", 1),
				(val_sub, ":quest_expiration_days", 1),
				(try_begin),
					(eq, ":quest_expiration_days", 5),
					(str_store_troop_name, 13, "$enlisted_lord"),
					(dialog_box, "@You have 5 days remaining in your leave from the party of {s13} before you will be declared a deserter.", "@Notice!"),
				(else_try),
					(is_between, ":quest_expiration_days", 2, 5),
					(assign, reg0, ":quest_expiration_days"),
					(display_message, "@You have {reg0} days left until you are declared as a deserter!"),
				(else_try),
					(eq, ":quest_expiration_days", 1),
					(str_store_troop_name, 13, "$enlisted_lord"),
					(dialog_box, "@You must check in with your commander {s13} immediately or you will be declared a deserter!", "@Warning!"),
				(try_end),
			(try_end)
		]),

]